name: dsci310
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - r-base            
  - r-irkernel
  - r-caret
  - r-dplyr
  - r-patchwork
  - r-tidyr
  - r-proc
  - r-ggplot2
  - pip
  - pip:
      - openpyxl




